apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-aws-eks
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-aws-eks
    meta.crossplane.io/license: Apache-2.0
spec:
  crossplane:
    version: ">=v1.13.2-0"
  dependsOn:
    - configuration: index.docker.io/ulucinar/configuration-aws-network
      version: "v0.45.0-c914fe18a92011992e32630ca4d0dba4a8f36242"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: "v0.15.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: "v0.9.0"
    - provider: index.docker.io/ulucinar/provider-aws-ec2
      version: "v0.45.0-c914fe18a92011992e32630ca4d0dba4a8f36242"
    - provider: index.docker.io/ulucinar/provider-aws-eks
      version: "v0.45.0-c914fe18a92011992e32630ca4d0dba4a8f36242"
    - provider: index.docker.io/ulucinar/provider-aws-iam
      version: "v0.45.0-c914fe18a92011992e32630ca4d0dba4a8f36242"
